import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import surveysRouter from "./surveys";
import customersRouter from "./customers";
import aiApprovalsRouter from "./ai_approvals";
import triggersRouter from "./triggers";
import auditLogsRouter from "./audit_logs";
import segmentsRouter from "./segments";
import geminiConversationsRouter from "./gemini/conversations";
import geminiPersonalizeRouter from "./gemini/personalize";
import importRouter from "./import";
import interactionRecordsRouter from "./interaction_records";
import surveyCampaignsRouter from "./survey_campaigns";
import cxAnalysesRouter from "./cx_analyses";
import companiesRouter from "./companies";
import analyticsRouter from "./analytics";
import anomaliesRouter from "./anomalies";
import nlpRouter from "./nlp";
import surveyQuestionsRouter from "./survey-questions";
import surveyTestSendRouter from "./survey-test-send";
import aiPersonalizeRouter from "./ai-personalize";
import settingsRouter from "./settings";
import apiKeysRouter from "./api-keys";
import usersRouter from "./users";
import approvalsRouter from "./approvals";
import invitationsRouter from "./invitations";
import permissionsRouter from "./permissions";
import tagTaxonomyRouter from "./tag-taxonomy";
import adminTestDataRouter from "./admin-test-data";
import v1Router from "./v1/index";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(analyticsRouter);
router.use(surveysRouter);
router.use(customersRouter);
router.use(aiApprovalsRouter);
router.use(triggersRouter);
router.use(auditLogsRouter);
router.use(segmentsRouter);
router.use(geminiConversationsRouter);
router.use(geminiPersonalizeRouter);
router.use(importRouter);
router.use(interactionRecordsRouter);
router.use(surveyCampaignsRouter);
router.use(cxAnalysesRouter);
router.use(companiesRouter);
router.use(anomaliesRouter);
router.use(nlpRouter);
router.use(surveyQuestionsRouter);
router.use(surveyTestSendRouter);
router.use(aiPersonalizeRouter);
router.use(settingsRouter);
router.use(apiKeysRouter);
router.use(usersRouter);
router.use(approvalsRouter);
router.use(invitationsRouter);
router.use(permissionsRouter);
router.use(tagTaxonomyRouter);
router.use(adminTestDataRouter);
router.use(v1Router);

export default router;
