// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-layouts/AsimetrikPanel.tsx": () => import("../components/mockups/login-layouts/AsimetrikPanel.tsx"),
  "./components/mockups/login-layouts/MerkeziKart.tsx": () => import("../components/mockups/login-layouts/MerkeziKart.tsx"),
  "./components/mockups/login-layouts/UstHero.tsx": () => import("../components/mockups/login-layouts/UstHero.tsx")
};
